import { Buffer } from "buffer";
import { Client as RefundableRsvpClient } from "refundable-rsvp";

import { asHex32, hexToBytes, secureRandomBytes } from "./bytes";
import {
  CommitPassError,
  contractError,
  isContractErrorName,
  type CancellationPolicy,
  type CheckInVoucher,
  type ContractErrorName,
  type EventStatus,
  type Hex32,
  type Hex64,
  type ReservationStatus,
  type StellarAddress,
  type UnixSeconds,
} from "./domain";
import {
  assertContractConfiguration,
  type CommitPassRuntimeConfig,
  type ContractRuntimeConfig,
} from "./config";
import {
  normalizeTransactionError,
  type TransactionStatus,
} from "./transaction";
import {
  generatedClientOptions,
  type StellarWalletAdapter,
} from "./wallet";

export interface OnChainEvent {
  id: Hex32;
  eventSalt: Hex32;
  organizer: StellarAddress;
  metadataHash: Hex32;
  startAt: UnixSeconds;
  checkInDeadline: UnixSeconds;
  endAt: UnixSeconds;
  token: StellarAddress;
  depositAmount: bigint;
  capacity: number;
  seatsReserved: number;
  outstandingDeposits: number;
  noShowBeneficiary: StellarAddress;
  cancellationPolicy: CancellationPolicy;
  scannerPublicKey: Hex32;
  status: EventStatus;
  createdAt: UnixSeconds;
}

export interface OnChainReservation {
  status: ReservationStatus;
  reservedAt: UnixSeconds;
  settledAt: UnixSeconds | null;
}

export interface CreateEventContractInput {
  eventSalt: Hex32;
  organizer: StellarAddress;
  metadataHash: Hex32;
  startAt: UnixSeconds;
  checkInDeadline: UnixSeconds;
  endAt: UnixSeconds;
  token: StellarAddress;
  depositAmount: bigint;
  capacity: number;
  noShowBeneficiary: StellarAddress | null;
  cancellationPolicy: CancellationPolicy;
  scannerPublicKey: Hex32;
}

export interface ContractWriteOptions {
  timeoutInSeconds?: number;
  onStatus?: (status: TransactionStatus) => void;
}

export interface ContractWriteReceipt<T> {
  result: T;
  hash?: string;
}

interface BindingErrorMessage {
  message: string;
}

interface BindingResult<T> {
  isOk(): boolean;
  isErr(): boolean;
  unwrap(): T;
  unwrapErr(): BindingErrorMessage;
}

interface BindingTransaction<T> {
  readonly result: T;
  signAndSend(options?: {
    watcher?: {
      onSubmitted(response?: unknown): void;
      onProgress(response?: unknown): void;
    };
  }): Promise<BindingSentTransaction<T>>;
}

interface BindingSentTransaction<T> {
  readonly result: T;
  readonly sendTransactionResponse?: unknown;
  readonly getTransactionResponse?: unknown;
}

interface BindingMethodOptions {
  timeoutInSeconds?: number;
  restore?: boolean;
}

type BindingEventStatus =
  | { tag: "Active"; values: void }
  | { tag: "Cancelled"; values: void };

type BindingReservationStatus =
  | { tag: "Reserved"; values: void }
  | { tag: "CheckedIn"; values: void }
  | { tag: "AttendeeRefunded"; values: void }
  | { tag: "AttendeeForfeited"; values: void }
  | { tag: "EventRefunded"; values: void }
  | { tag: "NoShow"; values: void };

type BindingCancellationPolicy =
  | { tag: "FullRefund"; values: void }
  | { tag: "ForfeitDeposit"; values: void };

interface BindingEvent<TBytes extends Uint8Array> {
  cancellation_policy: BindingCancellationPolicy;
  capacity: number;
  check_in_deadline: bigint;
  created_at: bigint;
  deposit_amount: bigint;
  end_at: bigint;
  event_id: TBytes;
  event_salt: TBytes;
  metadata_hash: TBytes;
  no_show_beneficiary: string;
  organizer: string;
  outstanding_deposits: number;
  scanner_public_key: TBytes;
  seats_reserved: number;
  start_at: bigint;
  status: BindingEventStatus;
  token: string;
}

interface BindingReservation {
  reserved_at: bigint;
  settled_at: bigint | undefined;
  status: BindingReservationStatus;
}

interface BindingEventConfig<TBytes extends Uint8Array> {
  cancellation_policy: BindingCancellationPolicy;
  capacity: number;
  check_in_deadline: bigint;
  deposit_amount: bigint;
  end_at: bigint;
  event_salt: TBytes;
  metadata_hash: TBytes;
  no_show_beneficiary: string | undefined;
  scanner_public_key: TBytes;
  start_at: bigint;
  token: string;
}

interface BindingCheckInVoucher<TBytes extends Uint8Array> {
  attendee: string;
  checked_in_at: bigint;
  event_id: TBytes;
  expires_at: bigint;
  nonce: TBytes;
}

/**
 * Structural subset of the client generated by:
 *
 * `stellar-js generate --wasm refundable_rsvp.wasm`
 *
 * Keeping this interface local means the app compiles in demo mode before a
 * deployment-specific generated package exists. Once generated, its `Client`
 * is passed directly to `GeneratedRefundableRsvpAdapter`.
 */
export interface RefundableRsvpGeneratedClient<
  TBytes extends Uint8Array,
> {
  reserve(
    input: { event_id: TBytes; attendee: string },
    options?: BindingMethodOptions,
  ): Promise<BindingTransaction<BindingResult<BindingReservation>>>;
  get_event(
    input: { event_id: TBytes },
    options?: BindingMethodOptions,
  ): Promise<BindingTransaction<BindingResult<BindingEvent<TBytes>>>>;
  has_event(
    input: { event_id: TBytes },
    options?: BindingMethodOptions,
  ): Promise<BindingTransaction<boolean>>;
  cancel_event(
    input: { event_id: TBytes; organizer: string },
    options?: BindingMethodOptions,
  ): Promise<BindingTransaction<BindingResult<BindingEvent<TBytes>>>>;
  create_event(
    input: {
      organizer: string;
      config: BindingEventConfig<TBytes>;
    },
    options?: BindingMethodOptions,
  ): Promise<BindingTransaction<BindingResult<BindingEvent<TBytes>>>>;
  is_nonce_used(
    input: { event_id: TBytes; nonce: TBytes },
    options?: BindingMethodOptions,
  ): Promise<BindingTransaction<boolean>>;
  derive_event_id(
    input: {
      organizer: string;
      config: BindingEventConfig<TBytes>;
    },
    options?: BindingMethodOptions,
  ): Promise<BindingTransaction<TBytes>>;
  sweep_no_show(
    input: { event_id: TBytes; attendee: string },
    options?: BindingMethodOptions,
  ): Promise<BindingTransaction<BindingResult<BindingReservation>>>;
  get_reservation(
    input: { event_id: TBytes; attendee: string },
    options?: BindingMethodOptions,
  ): Promise<BindingTransaction<BindingResult<BindingReservation>>>;
  has_reservation(
    input: { event_id: TBytes; attendee: string },
    options?: BindingMethodOptions,
  ): Promise<BindingTransaction<boolean>>;
  voucher_message(
    input: { voucher: BindingCheckInVoucher<TBytes> },
    options?: BindingMethodOptions,
  ): Promise<BindingTransaction<TBytes>>;
  get_deposit_token(
    options?: BindingMethodOptions,
  ): Promise<BindingTransaction<string>>;
  cancel_reservation(
    input: { event_id: TBytes; attendee: string },
    options?: BindingMethodOptions,
  ): Promise<BindingTransaction<BindingResult<BindingReservation>>>;
  claim_event_refund(
    input: { event_id: TBytes; attendee: string },
    options?: BindingMethodOptions,
  ): Promise<BindingTransaction<BindingResult<BindingReservation>>>;
  update_scanner_key(
    input: {
      event_id: TBytes;
      organizer: string;
      scanner_public_key: TBytes;
    },
    options?: BindingMethodOptions,
  ): Promise<BindingTransaction<BindingResult<BindingEvent<TBytes>>>>;
  claim_check_in_refund(
    input: {
      event_id: TBytes;
      attendee: string;
      voucher: BindingCheckInVoucher<TBytes>;
      signature: TBytes;
    },
    options?: BindingMethodOptions,
  ): Promise<BindingTransaction<BindingResult<BindingReservation>>>;
}

export interface GeneratedRefundableRsvpAdapterOptions<
  TBytes extends Uint8Array,
> {
  config: CommitPassRuntimeConfig;
  client: RefundableRsvpGeneratedClient<TBytes>;
  /**
   * Generated bindings currently use `Buffer`; inject
   * `(hex) => Buffer.from(hex, "hex")` from the generated package integration.
   * A Uint8Array factory is enough for mocks and future generators.
   */
  bytesFromHex: (hex: string) => TBytes;
}

export class GeneratedRefundableRsvpAdapter<
  TBytes extends Uint8Array,
> {
  readonly config: ContractRuntimeConfig;
  private readonly client: RefundableRsvpGeneratedClient<TBytes>;
  private readonly bytesFromHex: (hex: string) => TBytes;

  constructor(options: GeneratedRefundableRsvpAdapterOptions<TBytes>) {
    assertContractConfiguration(options.config);
    this.config = options.config;
    this.client = options.client;
    this.bytesFromHex = options.bytesFromHex;
  }

  async getEvent(eventId: Hex32): Promise<OnChainEvent> {
    const transaction = await this.client.get_event({
      event_id: this.byteValue(eventId, 32),
    });
    const event = mapEvent(unwrapBindingResult(transaction.result));
    if (event.id !== eventId.toLowerCase()) {
      throw new Error("The contract returned an event with a mismatched ID.");
    }
    return event;
  }

  async hasEvent(eventId: Hex32): Promise<boolean> {
    const transaction = await this.client.has_event({
      event_id: this.byteValue(eventId, 32),
    });
    return transaction.result;
  }

  async getReservation(
    eventId: Hex32,
    attendee: StellarAddress,
  ): Promise<OnChainReservation> {
    const transaction = await this.client.get_reservation({
      event_id: this.byteValue(eventId, 32),
      attendee,
    });
    return mapReservation(unwrapBindingResult(transaction.result));
  }

  async hasReservation(
    eventId: Hex32,
    attendee: StellarAddress,
  ): Promise<boolean> {
    const transaction = await this.client.has_reservation({
      event_id: this.byteValue(eventId, 32),
      attendee,
    });
    return transaction.result;
  }

  async isNonceUsed(eventId: Hex32, nonce: Hex32): Promise<boolean> {
    const transaction = await this.client.is_nonce_used({
      event_id: this.byteValue(eventId, 32),
      nonce: this.byteValue(nonce, 32),
    });
    return transaction.result;
  }

  async getDepositToken(): Promise<StellarAddress> {
    const transaction = await this.client.get_deposit_token();
    return transaction.result;
  }

  async deriveEventId(input: CreateEventContractInput): Promise<Hex32> {
    this.validateEventInput(input);
    const transaction = await this.client.derive_event_id({
      organizer: input.organizer,
      config: this.bindingEventConfig(input),
    });
    return bytesToFixedHex(transaction.result, 32);
  }

  /**
   * The exact canonical Soroban XDR that the event scanner must sign.
   */
  async voucherMessage(voucher: CheckInVoucher): Promise<Uint8Array> {
    const transaction = await this.client.voucher_message({
      voucher: this.bindingVoucher(voucher),
    });
    return new Uint8Array(transaction.result);
  }

  createEvent(
    input: CreateEventContractInput,
    options?: ContractWriteOptions,
  ): Promise<ContractWriteReceipt<OnChainEvent>> {
    this.validateEventInput(input);
    return this.write(
      () =>
        this.client.create_event(
          {
            organizer: input.organizer,
            config: this.bindingEventConfig(input),
          },
          methodOptions(options),
        ),
      (result) => mapEvent(unwrapBindingResult(result)),
      options,
    );
  }

  reserve(
    eventId: Hex32,
    attendee: StellarAddress,
    options?: ContractWriteOptions,
  ): Promise<ContractWriteReceipt<OnChainReservation>> {
    return this.write(
      () =>
        this.client.reserve(
          { event_id: this.byteValue(eventId, 32), attendee },
          methodOptions(options),
        ),
      (result) => mapReservation(unwrapBindingResult(result)),
      options,
    );
  }

  updateScannerKey(
    eventId: Hex32,
    organizer: StellarAddress,
    scannerPublicKey: Hex32,
    options?: ContractWriteOptions,
  ): Promise<ContractWriteReceipt<OnChainEvent>> {
    return this.write(
      () =>
        this.client.update_scanner_key(
          {
            event_id: this.byteValue(eventId, 32),
            organizer,
            scanner_public_key: this.byteValue(scannerPublicKey, 32),
          },
          methodOptions(options),
        ),
      (result) => mapEvent(unwrapBindingResult(result)),
      options,
    );
  }

  cancelReservation(
    eventId: Hex32,
    attendee: StellarAddress,
    options?: ContractWriteOptions,
  ): Promise<ContractWriteReceipt<OnChainReservation>> {
    return this.write(
      () =>
        this.client.cancel_reservation(
          { event_id: this.byteValue(eventId, 32), attendee },
          methodOptions(options),
        ),
      (result) => mapReservation(unwrapBindingResult(result)),
      options,
    );
  }

  cancelEvent(
    eventId: Hex32,
    organizer: StellarAddress,
    options?: ContractWriteOptions,
  ): Promise<ContractWriteReceipt<OnChainEvent>> {
    return this.write(
      () =>
        this.client.cancel_event(
          { event_id: this.byteValue(eventId, 32), organizer },
          methodOptions(options),
        ),
      (result) => mapEvent(unwrapBindingResult(result)),
      options,
    );
  }

  claimEventRefund(
    eventId: Hex32,
    attendee: StellarAddress,
    options?: ContractWriteOptions,
  ): Promise<ContractWriteReceipt<OnChainReservation>> {
    return this.write(
      () =>
        this.client.claim_event_refund(
          { event_id: this.byteValue(eventId, 32), attendee },
          methodOptions(options),
        ),
      (result) => mapReservation(unwrapBindingResult(result)),
      options,
    );
  }

  sweepNoShow(
    eventId: Hex32,
    attendee: StellarAddress,
    options?: ContractWriteOptions,
  ): Promise<ContractWriteReceipt<OnChainReservation>> {
    return this.write(
      () =>
        this.client.sweep_no_show(
          { event_id: this.byteValue(eventId, 32), attendee },
          methodOptions(options),
        ),
      (result) => mapReservation(unwrapBindingResult(result)),
      options,
    );
  }

  claimCheckInRefund(
    input: {
      eventId: Hex32;
      attendee: StellarAddress;
      voucher: CheckInVoucher;
      signature: Hex64;
    },
    options?: ContractWriteOptions,
  ): Promise<ContractWriteReceipt<OnChainReservation>> {
    return this.write(
      () =>
        this.client.claim_check_in_refund(
          {
            event_id: this.byteValue(input.eventId, 32),
            attendee: input.attendee,
            voucher: this.bindingVoucher(input.voucher),
            signature: this.byteValue(input.signature, 64),
          },
          methodOptions(options),
        ),
      (result) => mapReservation(unwrapBindingResult(result)),
      options,
    );
  }

  private bindingVoucher(
    voucher: CheckInVoucher,
  ): BindingCheckInVoucher<TBytes> {
    return {
      attendee: voucher.attendee,
      checked_in_at: BigInt(voucher.checkedInAt),
      event_id: this.byteValue(voucher.eventId, 32),
      expires_at: BigInt(voucher.expiresAt),
      nonce: this.byteValue(voucher.nonce, 32),
    };
  }

  private bindingEventConfig(
    input: CreateEventContractInput,
  ): BindingEventConfig<TBytes> {
    return {
      cancellation_policy: policyToBinding(input.cancellationPolicy),
      capacity: input.capacity,
      check_in_deadline: BigInt(input.checkInDeadline),
      deposit_amount: input.depositAmount,
      end_at: BigInt(input.endAt),
      event_salt: this.byteValue(input.eventSalt, 32),
      metadata_hash: this.byteValue(input.metadataHash, 32),
      no_show_beneficiary: input.noShowBeneficiary ?? undefined,
      scanner_public_key: this.byteValue(input.scannerPublicKey, 32),
      start_at: BigInt(input.startAt),
      token: input.token,
    };
  }

  private validateEventInput(input: CreateEventContractInput): void {
    if (/^0{64}$/.test(input.eventSalt)) {
      throw contractError("InvalidEventSalt");
    }
    if (input.token !== this.config.xlmSacId) {
      throw contractError(
        "UnsupportedToken",
        "The event token must match this deployment's pinned XLM SAC.",
      );
    }
  }

  private byteValue(hex: string, length: 32 | 64): TBytes {
    // Validate before handing bytes to a generated binding.
    hexToBytes(hex, length);
    return this.bytesFromHex(hex);
  }

  private async write<TBinding, TResult>(
    build: () => Promise<BindingTransaction<TBinding>>,
    mapResult: (result: TBinding) => TResult,
    options?: ContractWriteOptions,
  ): Promise<ContractWriteReceipt<TResult>> {
    emitStatus(options, "simulating");
    try {
      const transaction = await build();
      emitStatus(options, "awaiting-signature");
      let hash: string | undefined;
      const sent = await transaction.signAndSend({
        watcher: {
          onSubmitted(response) {
            hash = extractTransactionHash(response) ?? hash;
            emitStatus(options, "submitted", hash);
          },
          onProgress(response) {
            hash = extractTransactionHash(response) ?? hash;
            emitStatus(options, "pending", hash);
          },
        },
      });
      hash =
        extractTransactionHash(sent.getTransactionResponse) ??
        extractTransactionHash(sent.sendTransactionResponse) ??
        hash;
      const result = mapResult(sent.result);
      emitStatus(options, "confirmed", hash);
      return { result, hash };
    } catch (cause) {
      const error = normalizeTransactionError(cause);
      options?.onStatus?.({
        phase: "failed",
        message: error.message,
        error,
        updatedAt: Date.now(),
      });
      throw cause;
    }
  }
}

function unwrapBindingResult<T>(result: BindingResult<T>): T {
  if (result.isOk()) {
    return result.unwrap();
  }
  const error = result.unwrapErr();
  if (isContractErrorName(error.message)) {
    throw contractError(error.message);
  }
  throw new CommitPassError(
    "InvalidVoucher",
    error.message || "The contract returned an unknown error.",
  );
}

function mapEvent<TBytes extends Uint8Array>(
  event: BindingEvent<TBytes>,
): OnChainEvent {
  return {
    id: bytesToFixedHex(event.event_id, 32),
    eventSalt: bytesToFixedHex(event.event_salt, 32),
    organizer: event.organizer,
    metadataHash: bytesToFixedHex(event.metadata_hash, 32),
    startAt: bigintTimestamp(event.start_at),
    checkInDeadline: bigintTimestamp(event.check_in_deadline),
    endAt: bigintTimestamp(event.end_at),
    token: event.token,
    depositAmount: event.deposit_amount,
    capacity: event.capacity,
    seatsReserved: event.seats_reserved,
    outstandingDeposits: event.outstanding_deposits,
    noShowBeneficiary: event.no_show_beneficiary,
    cancellationPolicy: event.cancellation_policy.tag,
    scannerPublicKey: bytesToFixedHex(event.scanner_public_key, 32),
    status: event.status.tag,
    createdAt: bigintTimestamp(event.created_at),
  };
}

function mapReservation(
  reservation: BindingReservation,
): OnChainReservation {
  return {
    status: reservation.status.tag,
    reservedAt: bigintTimestamp(reservation.reserved_at),
    settledAt:
      reservation.settled_at === undefined
        ? null
        : bigintTimestamp(reservation.settled_at),
  };
}

function policyToBinding(
  policy: CancellationPolicy,
): BindingCancellationPolicy {
  return { tag: policy, values: undefined };
}

function bigintTimestamp(value: bigint): UnixSeconds {
  const number = Number(value);
  if (!Number.isSafeInteger(number) || number < 0) {
    throw new RangeError("Contract timestamp is outside JavaScript's safe range.");
  }
  return number;
}

function bytesToFixedHex(bytes: Uint8Array, length: 32): Hex32 {
  if (bytes.length !== length) {
    throw new TypeError(`Expected ${length} bytes from the contract binding.`);
  }
  let output = "";
  for (const byte of bytes) {
    output += byte.toString(16).padStart(2, "0");
  }
  return output;
}

function methodOptions(
  options?: ContractWriteOptions,
): BindingMethodOptions | undefined {
  return options?.timeoutInSeconds
    ? {
        timeoutInSeconds: options.timeoutInSeconds,
        restore: true,
      }
    : { restore: true };
}

function emitStatus(
  options: ContractWriteOptions | undefined,
  phase:
    | "simulating"
    | "awaiting-signature"
    | "submitted"
    | "pending"
    | "confirmed",
  hash?: string,
): void {
  const messages = {
    simulating: "Preparing and simulating the transaction…",
    "awaiting-signature": "Confirm the transaction in your wallet…",
    submitted: "Transaction submitted.",
    pending: "Waiting for ledger confirmation…",
    confirmed: "Transaction confirmed.",
  };
  options?.onStatus?.({
    phase,
    message: messages[phase],
    hash,
    updatedAt: Date.now(),
  });
}

function extractTransactionHash(value: unknown): string | undefined {
  if (typeof value !== "object" || value === null) {
    return undefined;
  }
  const record = value as Record<string, unknown>;
  for (const key of ["txHash", "hash", "transactionHash"]) {
    if (typeof record[key] === "string" && record[key]) {
      return record[key];
    }
  }
  return undefined;
}

export function contractErrorFromBindingMessage(
  message: string,
): ContractErrorName | undefined {
  return isContractErrorName(message) ? message : undefined;
}

export type RealRefundableRsvpAdapter =
  GeneratedRefundableRsvpAdapter<Buffer>;

export function createSecureEventSalt(
  randomBytes: (length: number) => Uint8Array = secureRandomBytes,
): Hex32 {
  return asHex32(randomBytes(32));
}

/**
 * Instantiates the checked-in deployment binding. Contract mode and a real
 * contract ID are required; no placeholder deployment is substituted.
 *
 * Pass a wallet for write methods. Omitting it creates a read-only adapter for
 * event/reservation queries, event-ID derivation, and `voucher_message`.
 */
export function createRefundableRsvpAdapter(
  config: CommitPassRuntimeConfig,
  wallet?: StellarWalletAdapter,
): RealRefundableRsvpAdapter {
  assertContractConfiguration(config);
  const client = new RefundableRsvpClient(
    wallet
      ? generatedClientOptions(config, wallet)
      : {
          contractId: config.contractId,
          networkPassphrase: config.networkPassphrase,
          rpcUrl: config.rpcUrl,
          allowHttp: config.network === "standalone",
        },
  );
  return new GeneratedRefundableRsvpAdapter({
    config,
    client,
    bytesFromHex: (hex) => Buffer.from(hex, "hex"),
  });
}
